{"name": "test_two", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'x' in 'this'", "trace": "self = <test_yield.TestDemo object at 0x00000231C2C44978>\n\n    def test_two(self, ):\n        print(\"测试方法2\")\n        x = \"this\"\n>       assert 'x' in x\nE       AssertionError: assert 'x' in 'this'\n\ntest_yield.py:31: AssertionError"}, "attachments": [{"name": "stdout", "source": "d22faac7-d57f-459e-8390-849cdbbb2293-attachment.txt", "type": "text/plain"}], "start": 1596253914941, "stop": 1596253914941, "uuid": "267200df-cf52-484d-b2d2-8aead7e62706", "historyId": "db0597bb27bbd1a248b6257f354ab0a1", "testCaseId": "2da77b6d4cdae4e875ac0e523efe2fe5", "fullName": "test_yield.TestDemo#test_two", "labels": [{"name": "suite", "value": "test_yield"}, {"name": "subSuite", "value": "TestDemo"}, {"name": "host", "value": "fkey"}, {"name": "thread", "value": "18364-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_yield"}]}